In [20]:
import pandas as pd
import scrap

In [84]:
daggers = scrap.get_daggers()

In [85]:
daggers

[['Icon',
  'Name',
  'Damage',
  'Critical Bonus',
  'Durability',
  'Weight',
  'Stats Needed\nStat Bonuses',
  'Availability',
  'Special Note'],
 ["Bandit's Knife",
  'Dagger',
  'Dark Silver Tracer',
  'Ghost Blade',
  'Parrying Dagger',
  "Priscilla's Dagger"],
 ['56/0/0/0 Bleed 300 (Slashing)',
  '56/0/0/0 (Slashing/Thrust)',
  '75/0/0/0 (Slashing/Thrust)',
  '110/0/0/0 (Slashing/Thrust)',
  '54/0/0/0 (Slashing/Thrust)',
  '80/0/0/0 Bleed 500 Dark 110 (Slashing/Thrust)'],
 ['147', '131', '160', '127', '131', '100'],
 ['200', '200', '120', '100', '200', '100']]

In [86]:
columns = daggers.pop(0)
columns

['Icon',
 'Name',
 'Damage',
 'Critical Bonus',
 'Durability',
 'Weight',
 'Stats Needed\nStat Bonuses',
 'Availability',
 'Special Note']

In [87]:
columns.pop(0)
for i in range(3):
    columns.pop(5)
columns.pop(4)

'Weight'

In [88]:
columns

['Name', 'Damage', 'Critical Bonus', 'Durability']

In [89]:
daggers

[["Bandit's Knife",
  'Dagger',
  'Dark Silver Tracer',
  'Ghost Blade',
  'Parrying Dagger',
  "Priscilla's Dagger"],
 ['56/0/0/0 Bleed 300 (Slashing)',
  '56/0/0/0 (Slashing/Thrust)',
  '75/0/0/0 (Slashing/Thrust)',
  '110/0/0/0 (Slashing/Thrust)',
  '54/0/0/0 (Slashing/Thrust)',
  '80/0/0/0 Bleed 500 Dark 110 (Slashing/Thrust)'],
 ['147', '131', '160', '127', '131', '100'],
 ['200', '200', '120', '100', '200', '100']]

In [90]:
df = pd.DataFrame(daggers)

In [91]:
df = df.T

In [92]:
df

                    0                                              1    2    3
0      Bandit's Knife                  56/0/0/0 Bleed 300 (Slashing)  147  200
1              Dagger                     56/0/0/0 (Slashing/Thrust)  131  200
2  Dark Silver Tracer                     75/0/0/0 (Slashing/Thrust)  160  120
3         Ghost Blade                    110/0/0/0 (Slashing/Thrust)  127  100
4     Parrying Dagger                     54/0/0/0 (Slashing/Thrust)  131  200
5  Priscilla's Dagger  80/0/0/0 Bleed 500 Dark 110 (Slashing/Thrust)  100  100

In [72]:
df.

,0,1,2,3,4,5
0,Bandit's Knife,Dagger,Dark Silver Tracer,Ghost Blade,Parrying Dagger,Priscilla's Dagger
1,56/0/0/0 Bleed 300 (Slashing),56/0/0/0 (Slashing/Thrust),75/0/0/0 (Slashing/Thrust),110/0/0/0 (Slashing/Thrust),54/0/0/0 (Slashing/Thrust),80/0/0/0 Bleed 500 Dark 110 (Slashing/Thrust)
2,147,131,160,127,131,100
3,200,200,120,100,200,100